config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do
    get 'ban'
    get 'unban'
  end

  resources :exchanges
  resources :reports
  resources :books do
    collection do
      get 'sell'
      post 'create_sell'
    end
    resources :listings do
      get 'buy'
      resources :offers
    end
 
  end

  match '/pages/terms' => "pages#terms", :via => [:get], :as => 'terms'

  
  root 'application#landing'

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id           :integer          not null, primary key
#  description  :text
#  quality      :string
#  listing_type :string
#  min_price    :float
#  status       :boolean
#  book_id      :integer
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Listing < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
	has_many :offers, dependent: :destroy
	has_one :exchange, dependent: :destroy
	
	validates :quality, presence: true, inclusion: {in: QUALITIES.collect {|k,v| v}}
	validates :listing_type, presence: true, inclusion: {in: TYPES}
	validates :min_price, presence: true, :numericality => {:greater_than_or_equal_to => 0}
	#validate :check_listing

	def check_listing
		if (exchange_type.present? && exchange_type!="Borrow" && !min_price.present?)
			errors.add(:min_price, "need Min Price")
		end
		if (exchange_type.present? && exchange_type=="Auction" && !max_price.present?)
			errors.add(:max_price, "need Max Price")
		end

		if (min_price.present? && min_price<0)
			errors.add(:min_price, "Must be non-negative")
		end

		if (max_price.present? && max_price<0)
			errors.add(:max_price, "Must be non-negative")
		end
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :set_book
	before_filter :verify_ed, :only=>[:edit, :update, :destroy]

	#def index
	#	@book = Book.find(params[:book_id])
	#	@listings = @book.listings
	#end

	def buy
		@listing = Listing.find(params[:listing_id])
		if @listing.status && @listing.user_id != current_user.id
			@exchange = Exchange.new(listing_id: @listing.id, user_id: current_user.id)
			if @exchange.save	
				Mailrobot.notify_buyer(@exchange.user, @exchange.listing).deliver
	      Mailrobot.notify_seller(@exchange.user, @exchange.listing).deliver
				redirect_to @exchange.user, notice: "Sucessfully bought #{@listing.book.title}! An email will be sent to both you and the seller shortly."
	      @listing.status = false
				@listing.save
			else
				redirect_to books_path, alert: "Error. Could not purchase book."
			end
    else
    	redirect_to books_path, alert: "Cannot purchase book."
    end
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def new
		@listing = Listing.new(book_id: @book.id, listing_type: "Buy", status: true, user_id: current_user.id)
	end

	def create
		@listing = Listing.new(listing_params)
		if @listing.save
			redirect_to book_listing_path(@listing.book, @listing), notice:'Listing was created successfully'
		else
			render 'new'
		end
	end

	def edit
		@listing = Listing.find(params[:id])
	end

	def update
		@listing = Listing.find(params[:id])
		if @listing.update(listing_params)
			redirect_to book_listing_path(@listing.book, @listing), notice: 'Listing was successfully updated'
		else
			render 'edit'
		end
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy unless @listing.nil?
		redirect_to @book
	end

	private

	def set_book
		@book = Book.find(params[:book_id])
	end

	def verify_ed
		@listing = Listing.find(params[:id])
		redirect_to books_path unless @listing.status && (@listing.user_id == current_user.id || (can? :modify, Listing))
	end

	def listing_params
		params.require(:listing).permit( :description, :quality, :listing_type, :status, :min_price,  :course_id,  :user_id, :book_id)
	end


end

app/helpers/listings_helper.rb
module ListingsHelper
	
	def show_type(listing)
		case listing.listing_type
		when "Buy"
			content_tag(:span, "Buy", class: "label label-success label-as-badge")
		when "Auction"
			content_tag(:span, "Auction", class: "label label-warning label-as-badge")
		when "Borrow"
			content_tag(:span, "Borrow", class: "label label-info label-as-badge")
		end
	end

	def show_status(listing)
		if listing.status
			content_tag(:span, "Open", class: "label label-success label-as-badge")
		else
			content_tag(:span, "Closed", class: "label label-danger label-as-badge")
		end
	end

	def show_seller(listing)
		user = User.find(listing.user_id)
		"#{user.first} #{user.last}"
	end

	def show_quality(listing)
		QUALITIES.key(listing.quality)
	end	

end

app/views/listings/_form.html.erb
<div class="row col-md-10 col-md-offset-1">

<h2><%= controller.action_name.capitalize %> listing for: </h2>
<h1><%= @book.title %> <small><%= @book.author %></small></h1>
<br>
<%= simple_form_for([@book,@listing], html:{class:'form-horizontal'} ) do |f| %>
  
    <% f.error_notification %>

    <%= f.hidden_field :book_id %>
    <%= f.hidden_field :listing_type %>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :status %>

    <%= f.input :quality, collection: QUALITIES, label:'Select Condition'%>
    <%= f.input :description, placeholder: 'Description' %>
    <%= f.input :min_price, placeholder: 'X or X.XX', label: 'Price' %>

    <br>
    <h5>Average Selling Prices:</h5>
    <% prices = avg_prices(Book.find(params[:book_id])) %>
    New: <%= prices[0]? show_price(prices[0], 2) : "---" %><br>
    Like New: <%= prices[1]? show_price(prices[1], 2) : "---" %><br>
    Good: <%= prices[2]? show_price(prices[2], 2) : "---" %><br>
    Acceptable: <%= prices[3]? show_price(prices[3], 2) : "---" %><br>


    <div class='row text-center'>
   	 <%= f.submit nil, class:'btn btn-primary' %>
   	 <%= link_to 'Cancel', book_path(@book), class:'btn btn-default' %>
   	</div>

    <% end %>

</div>

   

app/views/listings/_listing.html.erb
<a href=<%= book_listing_path(listing.book, listing) %> class="thumbnail text-center"  style="text-decoration:none;" >
	<div class="caption" style="background:#<%= (listing.user == current_user)? "AAAAAA" : "FFFFFF" %>">
		<h2 ><%= show_price(listing.min_price, 0) %></h2>
		<h4><%= show_type(listing) %> </h4>
		<h4><%= show_quality(listing)%></h4>
	</div>
</a>

app/views/listings/edit.html.erb
<%= render 'form' %>

app/views/listings/new.html.erb
<%= render 'form' %>

app/views/listings/show.html.erb
<div class="page-header">
  <h1><%= show_price(@listing.min_price, 0) + " | "%> <small> Listing for <%= link_to(truncate(@listing.book.title, length:35), @listing.book) %>  <%= show_status(@listing) %></small>
  </h1>
</div>

<div class="row">
  <div class="col-sm-2">
    <%= show_cover(@listing.book, 150, 200) %>
  </div>

  <div class="col-sm-10">
  <br>
      <dl class="dl-horizontal">
        <dt>Listing Type</dt>
        <dd><%= @listing.listing_type %></dd>
        <dt>Quality</dt>
        <dd><%= show_quality(@listing) %></dd>
        <dt>Description</dt>
        <dd><%= @listing.description %></dd>
        <dt>Price</dt>
        <dd><%= show_price(@listing.min_price, 2) %></dd>
        <dt>Seller</dt>
        <dd><%= show_seller(@listing) %>  <%="(You!)" if @listing.user == current_user%> </dd>
      </dl>
  </div>
</div>

<!-- 
<% if @listing.user_id == current_user.id or  current_user.is?(:superuser) or current_user.is?(:admin)%>
      <br>
      <table class='table table-striped'>
        <thead>
          <tr>
            <th colspan="3"></th>
          </tr>
          <th>Offer</th>
          <th>Name</th>
          <th>Price</th>
          <% if can? :destroy, Offer %>
              <th>Options</th>
          <% end %>
        </thead>

        <tbody>
          <%= render @listing.offers %>
        </tbody>
      </table>
<% end %> 


<% @listing.offers.each do |offer| %>
      <% if offer.user_id == current_user.id %>
            <p style="text-align:left;">
                  <h3>You have made an offer of <%= show_price(offer.price, 2) %>  </span></h3>
            </p>
      <% end %>
<% end %>

<% if @listing.offers.size == 0 %>
            <p style="text-align:left;">
                  <h4>You have not made an offer for this listing</h4>
            </p>
<% end %>
-->


<% if @listing.status %>
  <div class='text-right'>
    <% if current_user.id != @listing.user_id %>
      <%= link_to fa_icon('dollar', text:'Buy Book'), book_listing_buy_path(@listing.book, @listing), class: 'btn btn-lg btn-primary', data: { confirm: 'Are you sure you want to purchase this book? (PLEASE ONLY CLICK BUY BUTTON ONCE)'  } %>
    <% end %>
    <br><br>
    <% if current_user == @listing.user || (can? :modify, Listing) %>
      <%= link_to fa_icon('pencil', text:'Edit Listing'), edit_book_listing_path(@listing.book, @listing), class: 'btn btn-sm btn-default' %>
      <%= link_to fa_icon('trash-o', text:'Delete Listing'),  book_listing_path(@listing.book, @listing), method: :delete, data: { confirm: 'Are you sure?'  }, class:'btn btn-sm btn-danger' %>
    <% end %>
  </div>

<% end %>