config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do
    get 'ban'
    get 'unban'
  end

  resources :exchanges
  resources :reports
  resources :books do
    collection do
      get 'sell'
      post 'create_sell'
    end
    resources :listings do
      get 'buy'
      resources :offers
    end
 
  end

  match '/pages/terms' => "pages#terms", :via => [:get], :as => 'terms'

  
  root 'application#landing'

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string
#  author     :string
#  isbn       :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
	
	has_many :listings, dependent: :destroy
	has_many :reports, dependent: :destroy

	validates :isbn, presence: true, uniqueness: true
	validate :is_valid_isbn

	def is_valid_isbn
		if !title.present?
			 errors.add(:isbn, "Invalid ISBN.")
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 include BooksHelper
 include ApplicationHelper
  load_and_authorize_resource

  def index
    if (params[:search])
      @books = Book.all.where("lower(title) LIKE ? OR lower(author) LIKE ?", "%#{params[:search]}%".downcase, "%#{params[:search]}%".downcase).order(:title)
    else
      @books = Book.all.order(:title)
    end
    temp = []
    @books.each do |book|
      book.listings.each do |listing|
        if SCHOOLS[listing.user.email.split("@")[1]] ==  SCHOOLS[current_user.email.split("@")[1]]
          temp.push book
          break
        end
      end
    end
    @books = temp
    @books = @books.first(32)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def sell
  end

   def create_sell
    book_hash = get_book(params[:isbn])
    if book_hash
      matches = Book.find_by_isbn(book_hash["isbn"]) 
      if matches.blank?
        @book = Book.new(isbn: book_hash["isbn"], title: title_upcase(book_hash["title"]), author: book_hash["authors_text"], image_url: book_hash["image"])
        if @book.save
          report = Report.create(book_id:@book.id, user_id: current_user.id, text:"BOOK CREATED: #{@book.title}")
          Mailrobot.admin_report(report).deliver
          redirect_to new_book_listing_path(@book), notice: 'Book created. Now add a listing for this book.'
        else
          render 'sell', alert: "Couldn't save book."
        end
      else
        redirect_to new_book_listing_path(matches), notice: "Book found! Now add a listing for this book."
      end   
    else
      redirect_to sell_books_path, alert: "Invalid ISBN. Could not find book."
    end
  end

  def create
    @book = Book.new(book_params)
    set_book(@book)
    if @book.save
      redirect_to @book, notice: 'Book created.'
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])
      @book.update(book_params)
      set_book(@book)
      if @book.save
        redirect_to @book, notice: 'Textbook Successfully Updated'
      else
        render 'edit'
      end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy unless @book.nil?
    redirect_to books_path, alert: 'Textbook Deleted'
  end

  private

  def book_params
    params[:book].permit(:title, :author, :isbn, :image_url)
  end
  
end

app/helpers/books_helper.rb
module BooksHelper

	def get_book(isbn)
		return nil if isbn.empty?
		isbn = isbn.gsub '-', ''
		isbn = isbn.gsub ' ', ''
		isbn = ISBN.thirteen(isbn) if isbn.length == 10

		url = "https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}"
		res = JSON.parse open(url).read

		if res['totalItems'] == 0 
			nil
		else
			info = res['items'].first['volumeInfo']
			title = info['title']
			if info['authors']
				authors_text = info['authors'].join(", ")
			else 
				authors_text = "No Author"
			end
			if info['imageLinks'] && info['imageLinks']['thumbnail']
				image = info['imageLinks']['thumbnail']
			else
				image = "book2.png"
			end

			{"title" => title, "authors_text" => authors_text, "isbn" => isbn, "image" => image}
		end
	end

	def set_book(book)
		book_hash = get_book(book.isbn)
		if (book_hash)
			book.isbn = book_hash["isbn"]
  		book.title = title_upcase(book_hash["title"])
  		book.author = book_hash["authors_text"]
  		book.image_url = book_hash["image"]
  	else
  		book.title = nil
  		book.author = nil
  	end
  end


	def title_upcase(ttl)
		ttl.split.map(&:capitalize).join(' ')
	end
		
	def rand_spacing(range)
		nums = Array.new(7)
		elem = rand(range)
		for i in [0..7] do
			if elem != nums[i]
				nums.push(elem)
			end
		end
		return nums
	end

	def avg_prices(book)
		newprice = 0
		likenewprice = 0
		goodprice = 0
		acceptprice = 0

		news = book.listings.where(quality: "0")
		likenews = book.listings.where(quality: "1")
		goods = book.listings.where(quality: "2")
		accepts = book.listings.where(quality: "3")

		news.each do |l|
			newprice += l.min_price/news.size
		end
		likenews.each do |l|
			likenewprice += l.min_price/likenews.size
		end
		goods.each do |l|
			goodprice += l.min_price/goods.size
		end
		accepts.each do |l|
			acceptprice += l.min_price/accepts.size
		end

		[news.size > 0? newprice : nil, likenews.size > 0? likenewprice : nil,
		 goods.size >0? goodprice : nil, accepts.size >0? acceptprice : nil]
	end

	def show_cover(book, width, height)
		image_tag(book.image_url, width: width, height: height)
	end


end

app/views/books/_book.html.erb
<div class="thumbnail thumbnail-book">

	<a href="<%= book_path(book) %>" style="text-decoration:none; color: #333333;">
	<br>
		<img src="<%= book.image_url %>" class="img-responsive" width="160" alt="No Book Cover">
		
		<div class="caption-static">
			<h4 class="resize"><%= truncate(book.title,length:20) %></h4>
		</div>

		<div class="caption-hover">
			<h4 class="resize"><%= book.title %></h4>
			<h5 class="resize"><%= book.author %></h5>
		</div>
	</a>
</div>

app/views/books/_form.html.erb
<div class="row col-md-10 col-md-offset-1">


<h1><%= controller.action_name.capitalize %> Book </h1>
<br>
<%= simple_form_for(@book, html:{class:'form-horizontal'} ) do |f| %>
  
    <% f.error_notification %>

    <%= f.input :isbn, placeholder: 'ISBN' %>

    <div class='row text-center'>
   	 <%= f.submit nil, class:'btn btn-primary' %>
   	 <%= link_to 'Cancel', :back, class:'btn btn-default' %>
   	</div>

<% end %>

</div>

   

app/views/books/_sell_form.html.erb
<div class="page-header">
  <h1>Search for a book to sell</h1>
</div>
<br>

<div class="row">

  <%= form_tag(create_sell_books_path, method: "post", :class => "form-horizontal", role: 'form') do %>
  
  <div class="col-xs-6 col-offset-1">
  	<%= text_field_tag :isbn, nil, :placeholder=>"ISBN", class: "form-control"%><br>
  	<%= link_to 'Cancel', books_path, class:'btn btn-default ' %>

  </div>
  <div class="col-xs-6">
  	<%= submit_tag "Search",  class: 'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<div class="page-header">	
	<h1>Books for Sale at  <%= image_tag( LOGOS[SCHOOLS[current_user.email.split("@")[1]]], class: "school_logo" ) %></h1>
</div>
<div class="row">
	<div class="col-sm-6">
		<form class="navbar-form" role="search">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Title or Author" name="search">
			</div>
			<button type="submit" id="search" class="btn btn-info btn-sm">Search</button>
		</form>
	</div>

	<div class="col-sm-6 text-right">
		<% if can? :modify, Book %>
			<%= link_to 'New Book', new_book_path, class:'btn btn-lg btn-primary'%>
		<% end %>
		<%= link_to fa_icon('usd', text:'Sell A Book'), sell_books_path, class:'btn btn-lg btn-primary'%>
	</div>
</div>
<br>


<% @books.each_slice(4) do |books| %>
	<div class="row">
		<% books.each do |book| %>
		<div class="col-xs-3">
			<%= render book %>
		</div>
		<% end %>
	</div>
<% end %>

<%= javascript_include_tag 'hover'%>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/sell.html.erb
<%=  render 'sell_form'%>

app/views/books/show.html.erb
<div class="page-header">
	<div class="row">
		<div class="col-sm-9">
			<br><br>
			<h1><%= @book.title%></h1>
			<h4><%=  @book.author%> </h4>
		</div>
		<div class="col-sm-3 text-right">
			<%= show_cover(@book, 120, 160) %>
		</div>
	</div>
</div>
<br>
<div class="row text-right">
<%= link_to "Sort by Price", book_path(@book, sort:"price"), class: 'btn btn-md btn-default' %>
<%= link_to "Sort by Quality", book_path(@book, sort:"quality"), class: 'btn btn-md btn-default' %>
<%= link_to fa_icon('exchange', text:'New Listing'), new_book_listing_path(@book), class: 'btn btn-md btn-primary' %>
</div><br>

<% listings = @book.listings.where(status: true) %>
<% listings = listings.select{|listing| same_school?(listing.user, current_user)} %>
<% buys = listings.select{ |l| l.listing_type = "Buy" } %>

<% if (params[:sort] == 'price') %>
	<% buys = buys.sort_by { |l| [l.min_price, l.quality] }  %>
<% elsif (params[:sort] == 'quality') %>
	<% buys = buys.sort_by { |l| [l.quality, l.min_price] }  %>
<% end %>


<% if listings.size == 0 %>
	<h1><small>No Current Listings for this Book :(</small></h1>
<% end %>

<div class="row">
    <% buys.each do |buy| %>
		<div class="col-xs-3">
			<%= render buy %>
		</div>
	<% end %>
</div>
<br><br>

<div class='text-right'>
	<%= link_to "Found an Error? Report this Book", new_report_path(book_id: @book.id), class: 'btn btn-sm btn-warning' %>

	<% if can? :modify, Book%>
		<%= link_to fa_icon('pencil', text:'Edit Book'), edit_book_path(@book), class: 'btn btn-sm btn-default' %>
	<% end %>
	
	<% if can? :destroy, Book %>
		<%= link_to fa_icon('trash-o', text:'Delete Book'),  @book, method: :delete, data: { confirm: 'WARNING: This will destroy all listings and exchanges associated with this book. Are you sure?'  }, class:'btn btn-sm btn-danger' %>
	<% end %>
</div>